/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as _dashboardRouteRouteImport } from './routes/__dashboard/route'
import { Route as _dashboardIndexRouteImport } from './routes/__dashboard/index'
import { Route as _dashboardAssistantRouteImport } from './routes/__dashboard/assistant'

const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const _dashboardRouteRoute = _dashboardRouteRouteImport.update({
  id: '/__dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const _dashboardIndexRoute = _dashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _dashboardRouteRoute,
} as any)
const _dashboardAssistantRoute = _dashboardAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => _dashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/landing': typeof LandingRoute
  '/assistant': typeof _dashboardAssistantRoute
  '/': typeof _dashboardIndexRoute
}
export interface FileRoutesByTo {
  '/landing': typeof LandingRoute
  '/assistant': typeof _dashboardAssistantRoute
  '/': typeof _dashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__dashboard': typeof _dashboardRouteRouteWithChildren
  '/landing': typeof LandingRoute
  '/__dashboard/assistant': typeof _dashboardAssistantRoute
  '/__dashboard/': typeof _dashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/landing' | '/assistant' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/landing' | '/assistant' | '/'
  id:
    | '__root__'
    | '/__dashboard'
    | '/landing'
    | '/__dashboard/assistant'
    | '/__dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _dashboardRouteRoute: typeof _dashboardRouteRouteWithChildren
  LandingRoute: typeof LandingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__dashboard': {
      id: '/__dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _dashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__dashboard/': {
      id: '/__dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _dashboardIndexRouteImport
      parentRoute: typeof _dashboardRouteRoute
    }
    '/__dashboard/assistant': {
      id: '/__dashboard/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof _dashboardAssistantRouteImport
      parentRoute: typeof _dashboardRouteRoute
    }
  }
}

interface _dashboardRouteRouteChildren {
  _dashboardAssistantRoute: typeof _dashboardAssistantRoute
  _dashboardIndexRoute: typeof _dashboardIndexRoute
}

const _dashboardRouteRouteChildren: _dashboardRouteRouteChildren = {
  _dashboardAssistantRoute: _dashboardAssistantRoute,
  _dashboardIndexRoute: _dashboardIndexRoute,
}

const _dashboardRouteRouteWithChildren = _dashboardRouteRoute._addFileChildren(
  _dashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  _dashboardRouteRoute: _dashboardRouteRouteWithChildren,
  LandingRoute: LandingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
