/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as _dashboardRouteRouteImport } from './routes/__dashboard/route'
import { Route as _dashboardIndexRouteImport } from './routes/__dashboard/index'
import { Route as _dashboardTasksRouteImport } from './routes/__dashboard/tasks'
import { Route as _dashboardProfileRouteImport } from './routes/__dashboard/profile'
import { Route as _dashboardCalendarRouteImport } from './routes/__dashboard/calendar'
import { Route as _dashboardAssistantRouteImport } from './routes/__dashboard/assistant'

const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const _dashboardRouteRoute = _dashboardRouteRouteImport.update({
  id: '/__dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const _dashboardIndexRoute = _dashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _dashboardRouteRoute,
} as any)
const _dashboardTasksRoute = _dashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => _dashboardRouteRoute,
} as any)
const _dashboardProfileRoute = _dashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => _dashboardRouteRoute,
} as any)
const _dashboardCalendarRoute = _dashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => _dashboardRouteRoute,
} as any)
const _dashboardAssistantRoute = _dashboardAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => _dashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/landing': typeof LandingRoute
  '/assistant': typeof _dashboardAssistantRoute
  '/calendar': typeof _dashboardCalendarRoute
  '/profile': typeof _dashboardProfileRoute
  '/tasks': typeof _dashboardTasksRoute
  '/': typeof _dashboardIndexRoute
}
export interface FileRoutesByTo {
  '/landing': typeof LandingRoute
  '/assistant': typeof _dashboardAssistantRoute
  '/calendar': typeof _dashboardCalendarRoute
  '/profile': typeof _dashboardProfileRoute
  '/tasks': typeof _dashboardTasksRoute
  '/': typeof _dashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__dashboard': typeof _dashboardRouteRouteWithChildren
  '/landing': typeof LandingRoute
  '/__dashboard/assistant': typeof _dashboardAssistantRoute
  '/__dashboard/calendar': typeof _dashboardCalendarRoute
  '/__dashboard/profile': typeof _dashboardProfileRoute
  '/__dashboard/tasks': typeof _dashboardTasksRoute
  '/__dashboard/': typeof _dashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/landing'
    | '/assistant'
    | '/calendar'
    | '/profile'
    | '/tasks'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/landing' | '/assistant' | '/calendar' | '/profile' | '/tasks' | '/'
  id:
    | '__root__'
    | '/__dashboard'
    | '/landing'
    | '/__dashboard/assistant'
    | '/__dashboard/calendar'
    | '/__dashboard/profile'
    | '/__dashboard/tasks'
    | '/__dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _dashboardRouteRoute: typeof _dashboardRouteRouteWithChildren
  LandingRoute: typeof LandingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__dashboard': {
      id: '/__dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _dashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__dashboard/': {
      id: '/__dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _dashboardIndexRouteImport
      parentRoute: typeof _dashboardRouteRoute
    }
    '/__dashboard/tasks': {
      id: '/__dashboard/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof _dashboardTasksRouteImport
      parentRoute: typeof _dashboardRouteRoute
    }
    '/__dashboard/profile': {
      id: '/__dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof _dashboardProfileRouteImport
      parentRoute: typeof _dashboardRouteRoute
    }
    '/__dashboard/calendar': {
      id: '/__dashboard/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof _dashboardCalendarRouteImport
      parentRoute: typeof _dashboardRouteRoute
    }
    '/__dashboard/assistant': {
      id: '/__dashboard/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof _dashboardAssistantRouteImport
      parentRoute: typeof _dashboardRouteRoute
    }
  }
}

interface _dashboardRouteRouteChildren {
  _dashboardAssistantRoute: typeof _dashboardAssistantRoute
  _dashboardCalendarRoute: typeof _dashboardCalendarRoute
  _dashboardProfileRoute: typeof _dashboardProfileRoute
  _dashboardTasksRoute: typeof _dashboardTasksRoute
  _dashboardIndexRoute: typeof _dashboardIndexRoute
}

const _dashboardRouteRouteChildren: _dashboardRouteRouteChildren = {
  _dashboardAssistantRoute: _dashboardAssistantRoute,
  _dashboardCalendarRoute: _dashboardCalendarRoute,
  _dashboardProfileRoute: _dashboardProfileRoute,
  _dashboardTasksRoute: _dashboardTasksRoute,
  _dashboardIndexRoute: _dashboardIndexRoute,
}

const _dashboardRouteRouteWithChildren = _dashboardRouteRoute._addFileChildren(
  _dashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  _dashboardRouteRoute: _dashboardRouteRouteWithChildren,
  LandingRoute: LandingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
